# Site settings
title: HackerCollider
header-img: img/home-bg.jpg
email: hackercollider@gmail.com
copyright_name: HackerCollider
description: "a blog for real nerds"
baseurl: ""
url: "https://hackercollider.github.io"
twitter_username: hackercollider
github_username:  hackercollider
facebook_username:  hackercollider
email_username:  hackercollider@gmail.com
disqus_shortname: hackercollider

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
